# Generated by Django 5.1.3 on 2024-11-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveys',
            name='entities',
        ),
        migrations.AddField(
            model_name='surveys',
            name='entities',
            field=models.ManyToManyField(blank=True, related_name='surveys', to='survey.entitys'),
        ),
    ]
