# Generated by Django 5.1.3 on 2024-11-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_text',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
