# Generated by Django 5.1.3 on 2024-11-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_remove_answer_answer_text_answer_answer_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_data',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
