# Generated by Django 5.1.3 on 2024-11-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_answer_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveys',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
